### ISSUE TITLE
Sample App won't run Catastrophic Failure

### ISSUE THREAD

**Issue by michael-hawker** [windows-toolkit/Microsoft.Toolkit.Win32#197] opened 2019-10-27 23:17 UTC
Caused by commit de0c7e250b86f8e366a1457a4b058d2ee0b5ccb8

## I'm submitting a...
- Regression

## Current behavior
Microsoft.Toolkit.Sample.WPF.App crashes on start with Catostrophic Error and note about running on latest SDK (which it is).

## Expected behavior
Should not crash.

## Minimal reproduction of the problem with instructions
Clone repo, launch sample app, crash

## Environment
```
Nuget Package(s): 

Package Version(s): 

Windows 10 Build Number:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [x] April 2019 Update (18362)
- [ ] Insider Build (build number: )

App min and target version:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [x] April 2019 Update (18362)
- [ ] Insider Build (xxxxx)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

Visual Studio 
- [ ] 2019 (version: 16.3.6)
```

**Comment by jtbrower** [comment] 2019-11-25 02:31
**I was moments away from posting this bug report over on the WinUI teams github page, but after a bit more research it appears it belongs over here.  Is there a work-around for this?  Out of curiosity what is the cause?**

**Describe the bug**
Following the example at [Host UWP in WPF APP](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/host-standard-control-with-xaml-islands) I ran the application and although I was able to write on the Ink Canvas and the Calendar Control worked _sometimes_ I am seeing an initial catastrophic failure with the following stack trace

**Catastrophic failure (0x8000FFFF (E_UNEXPECTED))** 

>    at **Windows.UI.Xaml.Application.get_Current()**
>    at Microsoft.Toolkit.Win32.UI.XamlHost.XamlApplicationExtensions.GetCurrentProvider()

and then that results in 11 occurrences of the following Debug Output print 

> Exception thrown: 'System.BadImageFormatException' in System.Private.CoreLib.dll

Surprisingly to me, none of those exceptions cause the app to crash.  However I can easily force the crash by trying to scroll the calendar through the months using the mouse scroll.  About 50% of the time the calendar stops rendering the UI and then crashes so quickly that I cannot catch the exception with Domain, Dispatcher or TaskScheduler exception handlers.  Not being able to catch the crash really makes me feel uneasy.  The Windows Event Log contains the following.

> Faulting application name: WpfApp1.exe, version: 1.0.0.0, time stamp: 0x5dbebebd
> Faulting module name: Windows.UI.Xaml.dll, version: 10.0.18362.449, time stamp: 0xb90db728
> Exception code: 0xc0000005
> Fault offset: 0x0000000000a5398d
> Faulting process id: 0x86dc
> Faulting application start time: 0x01d5a33105c0345f
> Faulting application path: D:\examplesNotInGit\WpfApp1\WpfApp1\bin\x64\Release\netcoreapp3.1\WpfApp1.exe
> Faulting module path: C:\Windows\System32\Windows.UI.Xaml.dll
> Report Id: 04d367c0-803d-4a5c-a9b9-7eaf1a608de1
> Faulting package full name: 
> Faulting package-relative application ID: 

**Steps to reproduce the bug**
Following either the tutorial located at [Host UWP in WPF APP](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/host-standard-control-with-xaml-islands) or running the attached project you will see the exceptions print on the console.  You can also place a breakpoint in the first chance exception handler I installed to break on the initial **Catastrophic Failure**.

Although I assume that these initial errors are the ultimate cause of the crash, you can cause the crash by trying to scroll quickly through the calendar.  It seems to be a timing related issue.  About 50% of the time the calendar will not render months beyond the current month displayed.  That's when you can crash the app with ease.

**Expected behavior**
Other than hoping the application doesn't crash, it would be nice if the crash was tossed up the stack so that I know about it before the application goes down without any sign or error.

**Screenshots**
**Errors on Console**
![image](https://user-images.githubusercontent.com/3423706/69506568-d36a7580-0ef4-11ea-8ea8-5e75b07dc00e.png)

**Calendar View Just before Crash**
In this screenshot you can see how the calendar is having trouble rendering.  When this happens if you attempt to scroll further into the future (I have been using my mouse scroll) then the application will go down without any popup or chance to log the exception.
![image](https://user-images.githubusercontent.com/3423706/69506663-3cea8400-0ef5-11ea-952b-c629cb706c00.png)

**Version Info**
My app is a direct consumer of the Microsoft.Toolkit.Wpf.UI.Controls 6.0.0 package, however it is an indirect consumer of Windows.UI.Xaml.dll, version: 10.0.18362.449 that appears to cause the crash. (Hopefully you are the proper team to report this to, I apologize if you are not).

**NuGet package version:** 
I was using Microsoft.Toolkit.Wpf.UI.Controls 6.0.0, but noticed the tutorial was speaking of pre-release versions so I tried pre-7.1 and that also caused the issue.  I tried running as both a 32bit and 64bit app for both assemblies involved in the solution.

**Windows 10 version 18362**
**Device form factor Desktop** (I did not test others)

**Additional context**
I am running this application on a laptop through Visual Studio Pro 2019 Preview 16.4.0 Preview 6.0 (which also crashes frequently).  The laptop has an NVidia RTX5000, Xeon E-2286M with 128GB ECC.  I spent a good 4 hours trying to figure out if I personally did something wrong, but I don't think I overlooked anything.  The bad image format gives me the feeling that the wrong assemblies are being loaded.

**Comment by Kyaa-dost** [comment] 2020-01-22 20:31
Closing this issue as it is already being worked on #210

**Comment by marb2000** [comment] 2020-08-09 06:43
I believe this is no longer an issue. So closing it.

**Closed by marb2000** 2020-08-09 06:43 UTC
Labels: WPF, XamlIslands :desert_island:, bug :bug:
