### ISSUE TITLE
MediaPlayerElement needs work

### ISSUE THREAD

**Issue by julesx** [windows-toolkit/Microsoft.Toolkit.Win32#140] opened 2019-07-05 02:49 UTC
## Current behavior
You cannot bind the Source property
There is no Play method
There is no Pause/Stop method
You cannot set the PosterSource property to an image file
Media failing does not trigger the MediaFailed event
Multiple binding errors on load
Putting the control into a window, playing a video, and then closing the window does not stop playback.

## Expected behavior
All of the above should work.  Currently this control is worse than the stock WPF MediaElement control, which is already not great.

## Minimal reproduction of the problem with instructions
    <controls:MediaPlayerElement
        AreTransportControlsEnabled="True"
        AutoPlay="True"
        Source="{Binding Path}" />

## Environment
Windows

Nuget Package(s): 
Microsoft.Toolkit.Wpf.UI.Controls 
Package Version(s): 
6.0.0-preview6.2
Windows 10 Build Number:
18362.207

App min and target version:
not sure??

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

Visual Studio 
- [ ] 2017 (version: )
- [ ] 2017 Preview (version: )
- [x] 2019

**Comment by Symbai** [comment] 2019-07-10 13:40
https://github.com/windows-toolkit/Microsoft.Toolkit.Win32/issues/106

**Comment by julesx** [comment] 2019-07-10 14:15
I did see issue 106 but it doesn’t seem to get the point across. 

Why would anyone choose to use this version of the control over the stock WPF version? 

Clearly a lot of work has gone into the xaml islands tech but without major improvements I’m not sure it’s worth it?

**Comment by Symbai** [comment] 2019-07-10 18:06
The problem is only that the WPF version of the MediaPlayerElement isn't the same as the UWP version (which for example allows to call Play() and allows to have controls etc. as mentioned in 106). But as far as I know it "hosts" it. And the problem is that the WPF part has been outsourced into a new (this) repo which seems to be "dead".

I've created 106 to mention that the current MediaPlayerElement heavily lacks of functionality. Functionality which is already part of the UWP version but is missing in the WPF version.

Your issue is basically about the same except that your request goes even further by asking for features the UWP version is missing too. That's why I put the link to 106 here just for completion, nothing else.

**Comment by michael-hawker** [comment] 2019-07-18 22:07
@marb2000 FYI, you have time to chat early next week?  Wondering if we need more guidance in the [toolkit docs](https://docs.microsoft.com/en-us/windows/communitytoolkit/controls/wpf-winforms/mediaplayerelement) around migrating from the WPF MediaElement control as well (as in UWP the functionality is split into two parts MediaPlayerElement and MediaPlayer)?

**Comment by michael-hawker** [comment] 2019-08-29 22:43
Going to close this as a duplicate of #106

**Closed by michael-hawker** 2019-08-29 22:43 UTC
Labels: XamlIslands
