### ISSUE TITLE
Critical: Cannot play DRM content with MediaPlayerElement using XAML Islands

### ISSUE THREAD

**Issue by QuantumDeveloper** [windows-toolkit/Microsoft.Toolkit.Win32#243] opened 2020-03-16 19:45 UTC
## Describe the bug

- [ ] Is this bug a regression in the toolkit?  If so, what toolkit version did you last see it work:

## Steps to Reproduce
I am trying to start Adaptive Media Source demo from UWP and apply it to WPF project using XAML islands. 
Issue here is that exactly the same code is correctly working on UWP, but throw WinRT errors in WPF.
I failed to make player work with DRM content on WPF. Without DRM it works just fine.
I am attahing [sample project](https://github.com/windows-toolkit/Microsoft.Toolkit.Win32/files/4340075/DRM.TEst.zip) with 2 projects (UWP amd WPF XAML Islands) That you see the difference.

On WPF it throws an exception like: `WinRT originate error - 0xC00D715B : 'The topology could not be successfully verified.'.`

Is there a quick fix available for this issue or this is some core based?

## Environment

```
NuGet Package(s): 

Package Version(s): 

Project .NET Version:
- [ ] .NET Framework (version: )
- [ ] .NET Core 3
- [x] .NET Core 3.1 Preview (version: )

Windows 10 Build Number:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [x] May 2019 Update (18362)
- [ ] Insider Build (build number: )

App min and target version:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [x] May 2019 Update (18362)
- [ ] Insider Build (xxxxx)

Device form factor:
- [ x ] Desktop
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

Visual Studio 
- [ ] 2017 (version: )
- [x] 2019 (version: ) 
- [x] 2019 Preview (version: )

```

**Comment by Kyaa-dost** [comment] 2020-03-16 20:41
@marb2000  ⬆️

**Comment by marb2000** [comment] 2020-03-16 21:10
Thanks @QuantumDeveloper for letting us know. I will circle back when I collect more info about this issue.

**Comment by QuantumDeveloper** [comment] 2020-03-16 21:12
@marb2000  Hope this will not take much time

**Comment by QuantumDeveloper** [comment] 2020-03-17 18:08
Is there any info about this issue? @marb2000 
Our project is now at a standstill because we cannot use media playback with DRM and there is actually no alternative for windows.
Can you give us some help with this, please?

**Comment by QuantumDeveloper** [comment] 2020-03-19 22:43
@Kyaa-dost  @marb2000 

This issue is critical for me, because your player is the only player, which could play DRM with PlayReady/Widevine on Desktop.
So, due to this issue I am stuck with video playback.

Guys, can you please share some feeedback?

**Comment by Kyaa-dost** [comment] 2020-03-19 23:31
@marb2000 I know you are busy with lots of other open issues but was wondering any update on this one as it seems to be critical?

**Comment by marb2000** [comment] 2020-03-20 00:32
I'm talking to MediaPlayer team. I need to collect the logs so they can figure out what is happening. When we know the cause, then we will see what are the next steps.

**Comment by marb2000** [comment] 2020-03-24 04:46
Logs were collected and sent to the team. It's backlog know waiting someone investigate it.

**Comment by Kyaa-dost** [comment] 2020-03-24 16:20
Thanks for the update @marb2000!

**Comment by marb2000** [comment] 2020-08-08 07:44
Unfortunately, this won't be fixed on system XAML and XAML Islands v1. We will revisit the issue for WinUI 3 in Desktop and Islands.

**Closed by marb2000** 2020-08-08 07:44 UTC
Labels: XamlIslands :desert_island:, bug :bug:, waiting_product_group_triage
