### ISSUE TITLE
3 warning occurred when building solution

### ISSUE THREAD

**Issue by sbanni** [windows-toolkit/Microsoft.Toolkit.Win32#241] opened 2020-03-06 20:50 UTC
create a new project following https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/host-custom-control-with-xaml-islands

Severity | Code | Description | Project | File | Line | Suppression State
-- | -- | -- | -- | -- | -- | --
Warning |   | The referenced component 'D:\Users\username\.nuget\packages\microsoft.toolkit.win32.ui.xamlapplication\6.0.0\build\..\lib\uap10.0\Microsoft.Toolkit.Win32.UI.XamlHost.winmd'   could not be found. | MyUWPApp |   |   |  
Warning |   | Because your app is being built as AnyCPU no Microsoft.VCRTForwarders.140 DLLs were copied to your ouput folder. Microsoft.VCRTForwarders.140 only supports x86 or x64 applications due to a C++ Runtime dependency. Please change your app project architecture to x86 or x64 in the Configuration Manager. | MyWpfApp | D:\Users\username\.nuget\packages\microsoft.vcrtforwarders.140\1.0.2-rc\build\netcoreapp2.0\Microsoft.VCRTForwarders.140.targets | 33 |  
Warning | MSB3270 | There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "D:\Users\username\source\repos\XamlIslands\MyUWPApp\bin\x86\Debug\MyUWPApp.exe", "x86". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project. | MyWpfApp | D:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets | 2081 |

**Comment by michael-hawker** [comment] 2020-03-11 20:13
@marb2000?

**Comment by hansmbakker** [comment] 2020-07-12 22:26
@marb2000 I believe this does not need a validation.

@sbanni 
- The first warning is not a problem. It think it is discussed in https://github.com/windows-toolkit/Microsoft.Toolkit.Win32/issues/240
- The 2nd and 3rd warning indicate that you are using an `AnyCPU` configuration. That won't work if you are working with Xaml Islands. You need to make sure your projects use an x64 or x86 configuration (especially the WPF/WinForms head end). UWP does not work with AnyCPU. See https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/host-custom-control-with-xaml-islands (search for `x86`)

**Comment by marb2000** [comment] 2020-08-09 06:13
Agree with @hansmbakker on his assessment. 
Closing this given it's a dupe of #240

**Closed by marb2000** 2020-08-09 06:13 UTC
Labels: XamlIslands :desert_island:, bug :bug:, needs_validate_repro
