### ISSUE TITLE
WebViewCompatible.Navigate hangs indefinitely when process is elevated

### ISSUE THREAD

**Issue by znakeeye** [windows-toolkit/Microsoft.Toolkit.Win32#265] opened 2020-05-14 14:29 UTC
The `WebViewCompatible` control is completely broken when the process is run as administrator. Simply create a WPF app, reference the NuGet (6.0.1) and add the following code. Run as administrator and watch the UI hang - forever.

## Sample code

```xml
<controls:WebViewCompatible x:Name="webView"/>
```

```c#
public MainWindow()
{
    InitializeComponent();
    Loaded += OnLoaded;
}

private void OnLoaded(object sender, RoutedEventArgs e)
{
    webView.Navigate("http://html5test.com");
}
``` 

## Environment

```
NuGet Package(s): 
`Microsoft.Toolkit.Wpf.UI.Controls.WebView`

Package Version(s): 
**6.0.1**

Windows 10 Build Number:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [X] October 2018 Update (17763)
- [ ] May 2019 Update (18362)
- [ ] Insider Build (build number: )

App min and target version:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [X] October 2018 Update (17763)
- [ ] May 2019 Update (18362)
- [ ] Insider Build (xxxxx)

Device form factor:
- [X] Desktop
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

Visual Studio 
- [ ] 2017 (version: )
- [ ] 2019 (version: ) 
- [X] 2019 (version: )

```

## Additional context
Targeting `.NET Framework 4.7.2.`.

**Comment by michael-hawker** [comment] 2020-05-15 17:32
Duplicate of #13

**Closed by michael-hawker** 2020-05-15 17:32 UTC
Labels: WebView :desktop_computer:
