### ISSUE TITLE
ColorSpectrum in ColorPicker causes crash in WindowsXAMLHost

### ISSUE THREAD

**Issue by chanallenk** [windows-toolkit/Microsoft.Toolkit.Win32#101] opened 2019-03-31 17:46 UTC
## I'm submitting a...

Bug report (I searched for similar issues and did not find one) 
 

## Current behavior

In a Windows Application Packaging project. (WPF) when using a ColorSpectrum or a ColorPicker with the WindowsXAMLHost, upon closing the application window, an exception occurs:

Exception thrown at 0x58205777 (threadpoolwinrt.dll) in WPFComponents.exe: 0xC0000005: Access violation reading location 0x00000000.

## Expected behavior

When creating a UWP ColorPicker or ColorSpectrum in XAML Islands, it should be able to exit properly without crashing.

## Minimal reproduction of the problem with instructions

1. Create a new Windows Application Packaging Project with a reference to a WPF project
2. In the MainWindow of WPF project, create a XAML Island that uses Windows.UI.Xaml.Controls.ColorPicker or Windows.UI.Xaml.Controls.Primitives.ColorSpectrum
3. Interact with the ColorPicker
4. Close the MainWindow, application will crash

## Environment

```
Nuget Package(s): 
Microsoft.Toolkit.Win32.UI.Controls.5.0.0
Microsoft.Toolkit.Wpf.UI.XamlHost.6.0.0-preview3
Microsoft.Toolkit.Wpf.UI.Controls.6.0.0-preview3

Windows 10 Build Number:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [X] Insider Build (build number:  18362.1)

App min and target version:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [X] Insider Build (18361)

Device form factor:
- [X] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

Visual Studio 
- [X] 2017 (version: 15.9.4)
- [ ] 2017 Preview (version: )

```

**Comment by michael-hawker** [comment] 2019-08-29 22:54
Looks like a duplicate of #151, missing .pri file which is fixed if you follow the documentation (see PR in progress from linked issue).

**Closed by michael-hawker** 2019-08-29 22:54 UTC
Labels: XamlIslands
