### ISSUE TITLE
How to make WebView work in WPF when app is running as administrator

### ISSUE THREAD

**Issue by NikasZalias** [windows-toolkit/Microsoft.Toolkit.Win32#63] opened 2019-01-10 14:56 UTC
## I'm submitting a...

Bug report (I searched for similar issues and did not find one) 
 

## Current behavior

Running WPF app as admin, WebView does not load.

## Expected behavior

Running WPF app as admin, WebView should load.

## Minimal reproduction of the problem with instructions

Run WPF app as admin and try open WebView.

## Environment

```
Nuget Package(s): 
Microsoft.Toolkit.Wpf.UI.Controls.WebView 5.1
Package Version(s): 

Windows 10 Build Number:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [x ] October 2018 Update (17763)
- [ ] Insider Build (build number: )

App min and target version:
- [x ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [ ] Insider Build (xxxxx)

Device form factor:
- [x ] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

Visual Studio 
- [ x] 2017 (version: )
- [ ] 2017 Preview (version: )

```

I'm aware of the problem that WebView does not work when the app is running as admin. But maybe there is a workaround? Because I want to cover both cases, running the app as admin and running app, not as admin.

**Comment by cuiliang** [comment] 2019-02-11 13:36
Also will not work if process is elevated by uiAccess="true". 
Need workaround...

**Comment by NikasZalias** [comment] 2019-03-04 14:27
Any news maybe?

**Comment by DivyaPoosala** [comment] 2019-03-10 18:32
Can anyone Help me to load webview when application uiAccess="true". Your response means a lot to me.

**Comment by michael-hawker** [comment] 2019-03-11 03:45
@joshholmes any info you can provide on this?

**Comment by michael-hawker** [comment] 2019-03-11 03:48
Duplicate of #13

**Closed by michael-hawker** 2019-03-11 03:48 UTC
Labels: WebView

**Comment by NikasZalias** [comment] 2019-07-05 07:49
Is there any new info about this?
