### ISSUE TITLE
AcrylicBrush with HostBackdrop unreliable in WindowsXamlHost

### ISSUE THREAD

**Issue by devsko** [windows-toolkit/Microsoft.Toolkit.Win32#91] opened 2019-03-08 16:46 UTC
## I'm submitting a...

 - Bug report (I searched for similar issues and did not find one) 
 

``` c#
        private void WindowsXamlHost_Initialized(object sender, EventArgs e)
        {
            var xamlGrid = new WUX.Controls.Grid
            {
                Background = new WUX.Media.AcrylicBrush
                {
                    BackgroundSource = WUX.Media.AcrylicBackgroundSource.HostBackdrop,
                    FallbackColor = Colors.Red,
                }
            };
            xamlHost.Child = xamlGrid;
        }
```

## Current behavior

When the application starts, the background is drawn with the fallback color. Most of the time the backdrop starts working after minimizing/restoring or some window focus switches.
(NOTE: Using a `CompositionEffectBrush` based on `compositor.CreateHostBackdropBrush`, works as expected)

## Expected behavior

Backdrop should be used at start.

## Environment

```
Microsoft.Toolkit.Wpf.UI.XamlHost (private build from branch 6.0.0 @ 1dbafae)
Windows Preview 10.0.18351.0
Windows SDK 10.0.18342.0
.NET Core 3.0.100-preview3-010431
VS 2019 Preview 4.1
```

**Comment by azchohfi** [comment] 2019-03-08 19:17
@marb2000 could you triage this? Thanks.

**Comment by michael-hawker** [comment] 2019-08-29 22:57
Closing this as a duplicate of #170 (that one has more details and info)

**Closed by michael-hawker** 2019-08-29 22:57 UTC
Labels: XamlIslands
