### ISSUE TITLE
XamlParseException when UWP usercontrol embeded in usercontrol

### ISSUE THREAD

**Issue by tranvyhor** [windows-toolkit/Microsoft.Toolkit.Win32#137] opened 2019-06-27 07:01 UTC
## I'm submitting a...
Bug report

## Current behavior
I've made an UWP library including two usercontrols inside:MyUserControl1 and MyUserControl2.MyUserControl2 is embed in MyUserControl1.When WPF hosts MyUserControl1 by XAML Island, XamlParseException occured with message 'XAML parsing failed'.Stack Trace:
   at Windows.UI.Xaml.Application.LoadComponent(Object component, Uri resourceLocator, ComponentResourceLocation componentResourceLocation)
   at ClassLibrary1.MyUserControl1.InitializeComponent() in C:\Work\CodeWorks\XamlIslands-master\19H1_Insider_Samples\WPF_Core3_With_UserControl\ClassLibrary1\obj\Debug\MyUserControl1.g.i.cs:line 33
   at ClassLibrary1.MyUserControl1..ctor() in C:\Work\CodeWorks\XamlIslands-master\19H1_Insider_Samples\WPF_Core3_With_UserControl\ClassLibrary1\MyUserControl1.xaml.cs:line 24

## Environment
Nuget Package(s): 
Microsoft.NETCore.Platforms 3.0.0-preview5.19224.8
Microsoft.Toolkit.Wpf.UI.XamlHost 6.0.0-preview6.2
Microsoft.NETCore.UniversalWindowsPlatform 6.2.8

Windows 10 Build Number:
- Windows 10 Pro version 1903 build number 18362.175

App min and target version:
- Version 1903 (18362)

Device form factor:
- Desktop

Visual Studio 
- 2019 (version: 16.1.4)

**Comment by michael-hawker** [comment] 2019-07-18 21:49
Thanks for reporting the issue @tranvyhor, do you have a link on GitHub or to a download of this sample repro project you can share?

**Comment by michael-hawker** [comment] 2019-08-29 22:44
Duplicate of #151.

**Closed by michael-hawker** 2019-08-29 22:44 UTC
Labels: XamlIslands, bug
