### ISSUE TITLE
XAML Island WindowsXamlHost is not working

### ISSUE THREAD

**Issue by rvinothrajendran** [windows-toolkit/Microsoft.Toolkit.Win32#105] opened 2019-04-14 09:16 UTC
I'm submitting a...

Bug report (I searched for similar issues and did not find one)

## Current behavior

In WPF checking InitialTypeName in the code behind page it throw an exception

private void WindowsXamlHost_ChildChanged(object sender, EventArgs e)
        {
            var host = (WindowsXamlHost)sender;
            var btnClick = host.Child as Windows.UI.Xaml.Controls.Button;
        }

In the var btnClick = host.**Child** as Windows.UI.Xaml.Controls.Button;
**Issue :** Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0012	The type 'UIElement' is defined in an assembly that is not referenced. You must add a reference to assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime'.

## Environment

Nuget Package(s): Microsoft.Toolkit.Wpf.UI.XamlHost

Package Version(s): 6.0.0-preview3

Windows 10 Build Number:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [X] Insider Build (build number: 18362)

App min and target version:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [X] Insider Build (18362)

Device form factor:
- [X] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

Visual Studio 
- [X] 2019 (version: )
- [ ] 2017 Preview (version: )

```

**Comment by ad1Dima** [comment] 2019-04-30 05:10
Did you try this: https://docs.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-enhance#first-set-up-your-project

**Comment by michael-hawker** [comment] 2019-08-29 22:53
Looks like a duplicate of #151.

**Closed by michael-hawker** 2019-08-29 22:53 UTC
Labels: XamlIslands
