### ISSUE TITLE
Cannot create control of type

### ISSUE THREAD

**Issue by 0xf005ba11** [windows-toolkit/Microsoft.Toolkit.Win32#188] opened 2019-10-12 19:24 UTC
I am interested in using the new xaml islands to host UWP controls in a WPF App. I have followed the sample at https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/host-custom-control-with-xaml-islands to get started. The results appeared to work, and I started making changes specific to my needs. Now, sometimes the WPF app will load and display the UWP control as expected. And other times it loads with a message "Cannot create control of type UiClasses.ManagerPage" in place of the UWP control.

Changes I made to the sample:

1. The UWP custom control project is renamed UiClasses.
2. The custom UWP control is renamed ManagerPage.
3. The WPF app includes an ActiveX wrapper created with aximp.exe, however the code is not used yet. This is a wrapper for MSTSCLib.
4. The WPF app references the System.Management nuget package.

I have done some investigation myself, and I think I have found the reason for the occasional "Cannot create control of type" message. When the solution is built in debug or release, quite a few extra files are placed in the result build directory. The first time I start with debugging or start without debugging, the application will launch and work correctly. However, a number of files are deleted from the build directory (I don't know by what). The second time I launch the application via visual studio, it will no longer work.

After building, there is a UiClasses (the UWP classes library project) folder that contains two files that are both deleted at the first run:
1. ManagerPage.xbf
2. UiClasses.xr.xml

If I attempt to run the WPF project executable directly via file explorer (not from visual studio), then it exhibits the same problem. If I manually restore the ManagerPage.xbf file that was deleted, then the UWP control will work as expected. Restoring this file in both debug and release builds fixes the issue.

It appears launching the app via Visual Studio is deleting files that are required for the custom UWP control to be loadable. There are quite a few additional files that get deleted, like the App.xbf that looks like it is for the XamlApplication in the UWP app project.

## Environment
NuGet Package(s): 
Microsoft.Toolkit.Wpf.UI.XamlHost (6.0.0-preview9.1)
Microsoft.Toolkit.Win32.UI.XamlApplication (6.0.0-preview9.1)

Package Version(s): 

Windows 10 Build Number:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [*] May 2019 Update (18362)
- [ ] Insider Build (build number: )

App min and target version:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [*] May 2019 Update (18362)
- [ ] Insider Build (xxxxx)

Device form factor:
- [*] Desktop
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

Visual Studio 
- [ ] 2017 (version: )
- [*] 2019 (version: 16.3.4) 
- [ ] 2019 Preview (version: )

**Comment by michael-hawker** [comment] 2019-10-16 17:52
@marb2000 @ocalvo any thoughts on this one?

**Comment by marb2000** [comment] 2019-10-16 20:03
We are working on the update 4 of VS2019  that will fix several build issues. I repro will help to test this scenario in a couple a weeks.

**Comment by michael-hawker** [comment] 2019-10-18 00:36
@0xf005ba11 would you be able to fork and make a branch off the sample with the changes you made that reproduce this issue?  Miguel can then consume that more easily to quickly test the upcoming VS update.  Thanks!

**Comment by marb2000** [comment] 2019-10-18 22:29
Certainly! But also If I have the repro I can test it on the internal builds right now and make sure is fixed.

**Comment by edetoc** [comment] 2019-11-15 09:49
@0xf005ba11 
I've been able to reproduce this "Cannot create control..." issue on VS 2019 16.3.9 with the sample provided in https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/host-custom-control-with-xaml-islands
However I no longer see the error with same sample on latest VS 2019 16.4.0 Preview 5. So looks like it is fixed now as previously mentionned by @marb2000

**Comment by Palatis** [comment] 2019-12-30 15:16
> 
> 
> @0xf005ba11
> I've been able to reproduce this "Cannot create control..." issue on VS 2019 16.3.9 with the sample provided in https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/host-custom-control-with-xaml-islands
> However I no longer see the error with same sample on latest VS 2019 16.4.0 Preview 5. So looks like it is fixed now as previously mentionned by @marb2000

It still randomly occurs.
usually, if I run the code (after some edit) for the first time it wouldn't be able to create the UWP control.
however if I re-run the code, it runs fine.

Steps to reproduce:
1. edit the code
2. hit "run" => "Cannot create control MyNamespace.ControlClass"
3. hit "restart" => runs fine.
4. goto 1 because that's how we do programming...

**Comment by marb2000** [comment] 2020-08-09 07:09
I believe that the new [instructions](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/host-custom-control-with-xaml-islands ) and NuGet updates fixed this issue. Closing the issue. @0xf005ba11, @edetoc, and @Palatis  thanks for contributing to the conversation.

**Closed by marb2000** 2020-08-09 07:09 UTC
Labels: WPF, XamlIslands :desert_island:
